# -*- ruby -*-

require 'rubygems'
require 'rake'
require 'rake/tasklib'

require 'src/helpers.rb'
require 'ftools'

desc "Compile Site"
task :"build-website" do
  missing_gems = []
  requirements = ['haml', 'uv']
  requirements.each do |requirement|
    begin
      require requirement
    rescue LoadError => e
      puts "The following gems are required to build the amp website: #{requirements.join(", ")}"
      puts "Install them as follows: gem install #{requirements.join(" ")}"
      exit
    end
  end
  Dir["src/**/*.haml"].reject {|item| item.split("/").last =~ /^_/}.each do |haml|
    FileUtils.makedirs(File.dirname("build" + haml[3..-6] + ".html"))
    File.open("build" + haml[3..-6] + ".html","w") do |out|
      puts "Building #{haml[3..-6]}"
      out.write render(haml)
    end
  end
  %w(css images scripts docs).each do |dir|
    if File.exist? "src/#{dir}/"
      sh "cp -r src/#{dir}/ build/#{dir}/"
    end
  end
end

task :default => :"build-website" do
end